-- fpacc64.vhd

-- Generated using ACDS version 16.0 211
-- modified to solve bug with Error(13880) 

library IEEE;
--library altera_fp_acc_custom_160;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fpacc64 is
	port (
		ao     : out std_logic;                                        --     ao.ao
		areset : in  std_logic                     := '0';             -- areset.reset
		clk    : in  std_logic                     := '0';             --    clk.clk
		en     : in  std_logic_vector(0 downto 0)  := (others => '0'); --     en.en
		n      : in  std_logic                     := '0';             --      n.n
		r      : out std_logic_vector(63 downto 0);                    --      r.r
		x      : in  std_logic_vector(63 downto 0) := (others => '0'); --      x.x
		xo     : out std_logic;                                        --     xo.xo
		xu     : out std_logic                                         --     xu.xu
	);
end entity fpacc64;

architecture rtl of fpacc64 is
	component fpacc64_altera_fp_acc_custom_160_bhzzlly is
		-- changed x, xo, xu, ao to vectors to match component IP
		port (
			clk    : in  std_logic                     := 'X';             -- clk
			areset : in  std_logic                     := 'X';             -- reset
			x      : in  std_logic_vector(63 downto 0) := (others => 'X'); -- x
			n      : in  std_logic_vector(0 downto 0)  := (others => 'X'); --                     := 'X';             -- n
			r      : out std_logic_vector(63 downto 0);                    -- r
			xo     : out std_logic_vector(0 downto 0)  := (others => 'X');                                        -- xo
			xu     : out std_logic_vector(0 downto 0)  := (others => 'X');                                        -- xu
			ao     : out std_logic_vector(0 downto 0)  := (others => 'X');                                        -- ao
			en     : in  std_logic_vector(0 downto 0)  := (others => 'X')  -- en
		);
	end component fpacc64_altera_fp_acc_custom_160_bhzzlly;
	
	signal n_s, xo_s, xu_s, ao_s : std_logic_vector(0 downto 0);	-- added for vector conversion

--	for fp_acc_custom_0 : fpacc64_altera_fp_acc_custom_160_bhzzlly
--		use entity altera_fp_acc_custom_160.fpacc64_altera_fp_acc_custom_160_bhzzlly;
begin

	fp_acc_custom_0 : component fpacc64_altera_fp_acc_custom_160_bhzzlly
		port map (
			clk    => clk,    --    clk.clk
			areset => areset, -- areset.reset
			x      => x,      --      x.x
			n      => n_s,      --      n.n
			r      => r,      --      r.r
			xo     => xo_s,     --     xo.xo
			xu     => xu_s,     --     xu.xu
			ao     => ao_s,     --     ao.ao
			en     => en      --     en.en
		);
	
	-- added for vector type conversion 
	n_s(0) <= n;
	xo <= xo_s(0);
	xu <= xu_s(0);
	ao <= ao_s(0);

end architecture rtl; -- of fpacc64
