add wave -r /* 
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/cmt_pipeline/data_in
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/cmt_pipeline/d_in_vld
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/cmt_pipeline/kernel_in
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/cmt_pipeline/k_in_vld
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/cmt_pipeline/stall
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/cmt_pipeline/data_out
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/cmt_pipeline/d_out_vld
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/cmt_pipeline/done
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/cmt_pipeline/go
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/input_size
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/dma/rd_size
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/dma/wr_size
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/dma/rd_done
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/dma/wr_done
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/input_done
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/pipe_done
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/afu/done
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/dma_ctrl/cci_rd_remaining_r
add wave -expand /ase_top/platform_shim_ccip_std_afu/ccip_std_afu/hal/dma_ctrl/cci_wr_remaining_r
run -all
